include("branchbound.jl")


## Chen and Huang Benchmark Proteins
ch_24 = "HHPPHPPHPPHPPHPPHPPHPPHH"
ch_25 = "PPHPPHHPPPPHHPPPPHHPPPPHH"
ch_36 = "PPPHHPPHHPPPPPHHHHHHHPPHHPPPPHHPPHPP"
ch_48 = "PPHPPHHPPHHPPPPPHHHHHHHHHHPPPPPPHHPPHHPPHPPHHHHH"
ch_60 = "PPHHHPHHHHHHHHPPPHHHHHHHHHHPHPPPHHHHHHHHHHHHPPPPHHHHHHPHHPHP"
ch_85 = "HHHHPPPPHHHHHHHHHHHHPPPPPPHHHHHHHHHHHHPPPHHHHHHHHHHHHPPPHHHHHHHHHHHHPPPHPPHHPPHHPPHPH"
ch_100 = "PPPHHPPHHHHPPHHHPHHPHHPHHHHPPPPPPPPHHHHHHPPHHHHHHPPPPPPPPPHPHHPHHHHHHHHHHHPPHHHPHHPHPPHPHHHPPPPPPHHH"

ch_huge = "HHPPHPHPHHPHPHPHHHPPHHHPPPHHHPPHHPHPHHHPPPHPHHHPPPPPHHHHHHHPPHHPHPHHPHPHHHHPHPHHHPHPHHPHPHHHPPHPHHHHPPPPHHPHPHPPHPHHPPHHPPPPHHHPPPHPPPHPPPPPPHHHPPHHPPHHHHPPPHHPHPPPHPHPHHPHHPPPPPPPHHHPPHPPPHPPHPHHPPPH"



## Solving:
pgfplotsx()
@time E, C, stats = folder(ch_huge; latticetype = :triangle, ρ_1 = 0.7, sample_limit = 150)

plot(chainvis(C, ch_huge, size = 3; linkalpha = 0.2), size = (1000,800))
