include("branchbound.jl")


## Chen and Huang Benchmark Proteins
ch_24 = "HHPPHPPHPPHPPHPPHPPHPPHH"
ch_25 = "PPHPPHHPPPPHHPPPPHHPPPPHH"
ch_36 = "PPPHHPPHHPPPPPHHHHHHHPPHHPPPPHHPPHPP"
ch_48 = "PPHPPHHPPHHPPPPPHHHHHHHHHHPPPPPPHHPPHHPPHPPHHHHH"
ch_60 = "PPHHHPHHHHHHHHPPPHHHHHHHHHHPHPPPHHHHHHHHHHHHPPPPHHHHHHPHHPHP"
ch_85 = "HHHHPPPPHHHHHHHHHHHHPPPPPPHHHHHHHHHHHHPPPHHHHHHHHHHHHPPPHHHHHHHHHHHHPPPHPPHHPPHHPPHPH"
ch_100 = "PPPHHPPHHHHPPHHHPHHPHHPHHHHPPPPPPPPHHHHHHPPHHHHHHPPPPPPPPPHPHHPHHHHHHHHHHHPPHHHPHHPHPPHPHHHPPPPPPHHH"

ch_huge = "HHPPHPHPHHPHPHPHHHPPHHHPPPHHHPPHHPHPHHHPPPHPHHHPPPPPHHHHHHHPPHHPHPHHPHPHHHHPHPHHHPHPHHPHPHHHPPHPHHHHPPPPHHPHPHPPHPHHPPHHPPPPHHHPPPHPPPHPPPPPPHHHPPHHPPHHHHPPPHHPHPPPHPHPHHPHHPPPPPPPHHHPPHPPPHPPHPHHPPPH"

ch_huge2 = "HHPPHPHPHHPHPHPHHHPPHHHPPPHHHPPHHPHPHHHPPPHPHHHPPPPPHHHHHHHPPHHPHPHHPHPHHHHPHPHHHPHPHHPHPHHHPPHPHHHHPPPPHHPHPHPPHPHHPPHHPPPPHHHPPPHPPPHPPPPPPHPPHHPPPPHHHPPPPHHHHHHHHHHHHHHHHHHHHHHHHHHHHHPPPHPPPHPPPHHHHPPPHHHHHHHPPPPPPPPHHPPPHHHPPHHPPHHHHPPPHHPHPPPHPHPHHPHHPPPPPPPHHHPPHPPPHPPHPHHPPPH"

## Solving:
@time E, C, stats = folder(ch_huge2; dims = 3, latticetype = :triangle, ρ_1 = 0.7, sample_limit = 50)

plot(chainvis(C, ch_huge2, size = 3; linkcolor = :red, linkalpha = 0.9), foreground = :white)

growth3 = @animate for i = 1:length(C)
    plot(chainvis(C[1:i], ch_huge2[1:i]; size = 7, linkalpha = 0.3), foreground = :white, size = (800,800))
end

gif(growth3, "Figures/growth3.gif", fps = 15)

